### ISSUE TITLE
snapshot based ICU burden simulation

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/trauma-team-international#32]
#### TODO

- [ ] add tiny randomness into inferred values
- [ ] add quantile visualization option
- [ ] refactor the code
- [ ] structure as self-contained module
- [ ] add starting value and number of days as input variables
